# spring.datasource defines the information needed to connect to the MySQL schema.

spring:
   datasource:
      username: pet_store
      password: pet_store
      url: jdbc:mysql://localhost:3306/pet_store

# This section tells JPA to create the data tables.

   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true